// GENERATED FILE - DO NOT EDIT
#include "coi_schema.h"

namespace coi {

const SchemaEntry SCHEMA[] = {
    {"dom", "get_body", {}, "DOMElement"},
    {"dom", "create_element", {{"string", "tag"}}, "DOMElement"},
    {"dom", "set_attribute", {{"DOMElement", "handle"}, {"string", "name"}, {"string", "value"}}, ""},
    {"dom", "get_attribute", {{"DOMElement", "handle"}, {"string", "name"}}, "string"},
    {"dom", "append_child", {{"DOMElement", "parent_handle"}, {"DOMElement", "child_handle"}}, ""},
    {"dom", "remove_element", {{"DOMElement", "handle"}}, ""},
    {"dom", "set_inner_html", {{"DOMElement", "handle"}, {"string", "html"}}, ""},
    {"dom", "set_inner_text", {{"DOMElement", "handle"}, {"string", "text"}}, ""},
    {"dom", "add_class", {{"DOMElement", "handle"}, {"string", "cls"}}, ""},
    {"dom", "remove_class", {{"DOMElement", "handle"}, {"string", "cls"}}, ""},
    {"dom", "add_click_listener", {{"DOMElement", "handle"}}, ""},
    {"canvas", "create_canvas", {{"string", "dom_id"}, {"float32", "width"}, {"float32", "height"}}, "Canvas"},
    {"canvas", "get_context", {{"Canvas", "canvas_handle"}, {"string", "context_type"}}, "CanvasContext2D"},
    {"canvas", "set_size", {{"Canvas", "handle"}, {"float32", "width"}, {"float32", "height"}}, ""},
    {"canvas", "set_fill_style", {{"CanvasContext2D", "handle"}, {"uint8", "r"}, {"uint8", "g"}, {"uint8", "b"}}, ""},
    {"canvas", "set_fill_style_str", {{"CanvasContext2D", "handle"}, {"string", "color"}}, ""},
    {"canvas", "fill_rect", {{"CanvasContext2D", "handle"}, {"float32", "x"}, {"float32", "y"}, {"float32", "w"}, {"float32", "h"}}, ""},
    {"canvas", "clear_rect", {{"CanvasContext2D", "handle"}, {"float32", "x"}, {"float32", "y"}, {"float32", "w"}, {"float32", "h"}}, ""},
    {"canvas", "stroke_rect", {{"CanvasContext2D", "handle"}, {"float32", "x"}, {"float32", "y"}, {"float32", "w"}, {"float32", "h"}}, ""},
    {"canvas", "set_stroke_style", {{"CanvasContext2D", "handle"}, {"uint8", "r"}, {"uint8", "g"}, {"uint8", "b"}}, ""},
    {"canvas", "set_stroke_style_str", {{"CanvasContext2D", "handle"}, {"string", "color"}}, ""},
    {"canvas", "set_line_width", {{"CanvasContext2D", "handle"}, {"float32", "width"}}, ""},
    {"canvas", "begin_path", {{"CanvasContext2D", "handle"}}, ""},
    {"canvas", "close_path", {{"CanvasContext2D", "handle"}}, ""},
    {"canvas", "move_to", {{"CanvasContext2D", "handle"}, {"float32", "x"}, {"float32", "y"}}, ""},
    {"canvas", "line_to", {{"CanvasContext2D", "handle"}, {"float32", "x"}, {"float32", "y"}}, ""},
    {"canvas", "stroke", {{"CanvasContext2D", "handle"}}, ""},
    {"canvas", "fill", {{"CanvasContext2D", "handle"}}, ""},
    {"canvas", "arc", {{"CanvasContext2D", "handle"}, {"float32", "x"}, {"float32", "y"}, {"float32", "radius"}, {"float32", "start_angle"}, {"float32", "end_angle"}}, ""},
    {"canvas", "fill_text", {{"CanvasContext2D", "handle"}, {"string", "text"}, {"float32", "x"}, {"float32", "y"}}, ""},
    {"canvas", "fill_text_f", {{"CanvasContext2D", "handle"}, {"string", "fmt"}, {"float32", "val"}, {"float32", "x"}, {"float32", "y"}}, ""},
    {"canvas", "fill_text_i", {{"CanvasContext2D", "handle"}, {"string", "fmt"}, {"int32", "val"}, {"float32", "x"}, {"float32", "y"}}, ""},
    {"canvas", "set_font", {{"CanvasContext2D", "handle"}, {"string", "font"}}, ""},
    {"canvas", "set_text_align", {{"CanvasContext2D", "handle"}, {"string", "align"}}, ""},
    {"canvas", "draw_image", {{"CanvasContext2D", "handle"}, {"Image", "img_handle"}, {"float32", "x"}, {"float32", "y"}}, ""},
    {"canvas", "translate", {{"CanvasContext2D", "handle"}, {"float32", "x"}, {"float32", "y"}}, ""},
    {"canvas", "rotate", {{"CanvasContext2D", "handle"}, {"float32", "angle"}}, ""},
    {"canvas", "scale", {{"CanvasContext2D", "handle"}, {"float32", "x"}, {"float32", "y"}}, ""},
    {"canvas", "save", {{"CanvasContext2D", "handle"}}, ""},
    {"canvas", "restore", {{"CanvasContext2D", "handle"}}, ""},
    {"canvas", "log_canvas_info", {{"Canvas", "handle"}}, ""},
    {"canvas", "set_global_alpha", {{"CanvasContext2D", "handle"}, {"float32", "alpha"}}, ""},
    {"canvas", "set_line_cap", {{"CanvasContext2D", "handle"}, {"string", "cap"}}, ""},
    {"canvas", "set_line_join", {{"CanvasContext2D", "handle"}, {"string", "join"}}, ""},
    {"canvas", "set_shadow", {{"CanvasContext2D", "handle"}, {"float32", "blur"}, {"float32", "off_x"}, {"float32", "off_y"}, {"string", "color"}}, ""},
    {"canvas", "bezier_curve_to", {{"CanvasContext2D", "handle"}, {"float32", "cp1x"}, {"float32", "cp1y"}, {"float32", "cp2x"}, {"float32", "cp2y"}, {"float32", "x"}, {"float32", "y"}}, ""},
    {"canvas", "quadratic_curve_to", {{"CanvasContext2D", "handle"}, {"float32", "cpx"}, {"float32", "cpy"}, {"float32", "x"}, {"float32", "y"}}, ""},
    {"canvas", "rect", {{"CanvasContext2D", "handle"}, {"float32", "x"}, {"float32", "y"}, {"float32", "w"}, {"float32", "h"}}, ""},
    {"canvas", "clip", {{"CanvasContext2D", "handle"}}, ""},
    {"canvas", "stroke_text", {{"CanvasContext2D", "handle"}, {"string", "text"}, {"float32", "x"}, {"float32", "y"}}, ""},
    {"canvas", "set_text_baseline", {{"CanvasContext2D", "handle"}, {"string", "baseline"}}, ""},
    {"canvas", "set_global_composite_operation", {{"CanvasContext2D", "handle"}, {"string", "op"}}, ""},
    {"canvas", "draw_image_scaled", {{"CanvasContext2D", "handle"}, {"Image", "img_handle"}, {"float32", "x"}, {"float32", "y"}, {"float32", "w"}, {"float32", "h"}}, ""},
    {"canvas", "draw_image_full", {{"CanvasContext2D", "handle"}, {"Image", "img_handle"}, {"float32", "sx"}, {"float32", "sy"}, {"float32", "sw"}, {"float32", "sh"}, {"float32", "dx"}, {"float32", "dy"}, {"float32", "dw"}, {"float32", "dh"}}, ""},
    {"canvas", "reset_transform", {{"CanvasContext2D", "handle"}}, ""},
    {"canvas", "ellipse", {{"CanvasContext2D", "handle"}, {"float32", "x"}, {"float32", "y"}, {"float32", "radius_x"}, {"float32", "radius_y"}, {"float32", "rotation"}, {"float32", "start_angle"}, {"float32", "end_angle"}, {"uint8", "counter_clockwise"}}, ""},
    {"canvas", "arc_to", {{"CanvasContext2D", "handle"}, {"float32", "x1"}, {"float32", "y1"}, {"float32", "x2"}, {"float32", "y2"}, {"float32", "radius"}}, ""},
    {"canvas", "set_transform", {{"CanvasContext2D", "handle"}, {"float32", "a"}, {"float32", "b"}, {"float32", "c"}, {"float32", "d"}, {"float32", "e"}, {"float32", "f"}}, ""},
    {"canvas", "transform", {{"CanvasContext2D", "handle"}, {"float32", "a"}, {"float32", "b"}, {"float32", "c"}, {"float32", "d"}, {"float32", "e"}, {"float32", "f"}}, ""},
    {"canvas", "set_miter_limit", {{"CanvasContext2D", "handle"}, {"float32", "limit"}}, ""},
    {"canvas", "set_image_smoothing_enabled", {{"CanvasContext2D", "handle"}, {"uint8", "enabled"}}, ""},
    {"canvas", "measure_text_width", {{"CanvasContext2D", "handle"}, {"string", "text"}}, "float32"},
    {"input", "init_keyboard", {}, ""},
    {"input", "init_mouse", {{"DOMElement", "handle"}}, ""},
    {"input", "request_pointer_lock", {{"DOMElement", "handle"}}, ""},
    {"input", "exit_pointer_lock", {}, ""},
    {"system", "log", {{"string", "msg"}}, ""},
    {"system", "warn", {{"string", "msg"}}, ""},
    {"system", "error", {{"string", "msg"}}, ""},
    {"system", "set_main_loop", {{"func_ptr", "func"}}, ""},
    {"system", "set_title", {{"string", "title"}}, ""},
    {"system", "reload", {}, ""},
    {"system", "open_url", {{"string", "url"}}, ""},
    {"system", "request_fullscreen", {{"DOMElement", "handle"}}, ""},
    {"system", "get_time", {}, "float64"},
    {"system", "get_date_now", {}, "float64"},
    {"storage", "set_item", {{"string", "key"}, {"string", "value"}}, ""},
    {"storage", "remove_item", {{"string", "key"}}, ""},
    {"storage", "clear", {}, ""},
    {"audio", "create_audio", {{"string", "src"}}, "Audio"},
    {"audio", "play", {{"Audio", "handle"}}, ""},
    {"audio", "pause", {{"Audio", "handle"}}, ""},
    {"audio", "set_volume", {{"Audio", "handle"}, {"float32", "vol"}}, ""},
    {"audio", "set_loop", {{"Audio", "handle"}, {"uint8", "loop"}}, ""},
    {"audio", "get_current_time", {{"Audio", "handle"}}, "float32"},
    {"audio", "get_duration", {{"Audio", "handle"}}, "float32"},
    {"websocket", "create", {{"string", "url"}, {"uint32", "events"}}, "WebSocket"},
    {"websocket", "send", {{"WebSocket", "handle"}, {"string", "msg"}}, ""},
    {"websocket", "close", {{"WebSocket", "handle"}}, ""},
    {"fetch", "get", {{"string", "url"}}, "FetchRequest"},
    {"fetch", "post", {{"string", "url"}, {"string", "body"}}, "FetchRequest"},
    {"image", "load", {{"string", "src"}}, "Image"},
    {"webgl", "viewport", {{"WebGLContext", "ctx_handle"}, {"int32", "x"}, {"int32", "y"}, {"int32", "width"}, {"int32", "height"}}, ""},
    {"webgl", "clear_color", {{"WebGLContext", "ctx_handle"}, {"float32", "r"}, {"float32", "g"}, {"float32", "b"}, {"float32", "a"}}, ""},
    {"webgl", "clear", {{"WebGLContext", "ctx_handle"}, {"uint32", "mask"}}, ""},
    {"webgl", "create_shader", {{"WebGLContext", "ctx_handle"}, {"uint32", "type"}, {"string", "source"}}, "WebGLShader"},
    {"webgl", "create_program", {{"WebGLContext", "ctx_handle"}}, "WebGLProgram"},
    {"webgl", "attach_shader", {{"WebGLContext", "ctx_handle"}, {"WebGLProgram", "prog_handle"}, {"WebGLShader", "shader_handle"}}, ""},
    {"webgl", "link_program", {{"WebGLContext", "ctx_handle"}, {"WebGLProgram", "prog_handle"}}, ""},
    {"webgl", "bind_attrib_location", {{"WebGLContext", "ctx_handle"}, {"WebGLProgram", "prog_handle"}, {"uint32", "index"}, {"string", "name"}}, ""},
    {"webgl", "use_program", {{"WebGLContext", "ctx_handle"}, {"WebGLProgram", "prog_handle"}}, ""},
    {"webgl", "create_buffer", {{"WebGLContext", "ctx_handle"}}, "WebGLBuffer"},
    {"webgl", "bind_buffer", {{"WebGLContext", "ctx_handle"}, {"uint32", "target"}, {"WebGLBuffer", "buf_handle"}}, ""},
    {"webgl", "buffer_data", {{"WebGLContext", "ctx_handle"}, {"uint32", "target"}, {"uint32", "data_ptr"}, {"uint32", "data_len"}, {"uint32", "usage"}}, ""},
    {"webgl", "enable_vertex_attrib_array", {{"WebGLContext", "ctx_handle"}, {"uint32", "index"}}, ""},
    {"webgl", "enable", {{"WebGLContext", "ctx_handle"}, {"uint32", "cap"}}, ""},
    {"webgl", "get_uniform_location", {{"WebGLContext", "ctx_handle"}, {"WebGLProgram", "prog_handle"}, {"string", "name"}}, "WebGLUniform"},
    {"webgl", "uniform_1f", {{"WebGLContext", "ctx_handle"}, {"WebGLUniform", "loc_handle"}, {"float32", "val"}}, ""},
    {"webgl", "vertex_attrib_pointer", {{"WebGLContext", "ctx_handle"}, {"uint32", "index"}, {"int32", "size"}, {"uint32", "type"}, {"uint8", "normalized"}, {"int32", "stride"}, {"int32", "offset"}}, ""},
    {"webgl", "draw_arrays", {{"WebGLContext", "ctx_handle"}, {"uint32", "mode"}, {"int32", "first"}, {"int32", "count"}}, ""},
    {"wgpu", "request_adapter", {}, ""},
    {"wgpu", "request_device", {{"WGPUAdapter", "adapter_handle"}}, ""},
    {"wgpu", "get_queue", {{"WGPUDevice", "device_handle"}}, "WGPUQueue"},
    {"wgpu", "create_shader_module", {{"WGPUDevice", "device_handle"}, {"string", "code"}}, "WGPUShaderModule"},
    {"wgpu", "create_command_encoder", {{"WGPUDevice", "device_handle"}}, "WGPUCommandEncoder"},
    {"wgpu", "configure", {{"WGPUContext", "context_handle"}, {"WGPUDevice", "device_handle"}, {"string", "format"}}, ""},
    {"wgpu", "get_current_texture_view", {{"WGPUContext", "context_handle"}}, "WGPUTextureView"},
    {"wgpu", "begin_render_pass", {{"WGPUCommandEncoder", "encoder_handle"}, {"WGPUTextureView", "view_handle"}, {"float32", "r"}, {"float32", "g"}, {"float32", "b"}, {"float32", "a"}}, "WGPURenderPass"},
    {"wgpu", "end_pass", {{"WGPURenderPass", "pass_handle"}}, ""},
    {"wgpu", "finish_encoder", {{"WGPUCommandEncoder", "encoder_handle"}}, "WGPUCommandBuffer"},
    {"wgpu", "queue_submit", {{"WGPUQueue", "queue_handle"}, {"WGPUCommandBuffer", "command_buffer_handle"}}, ""},
    {"wgpu", "create_render_pipeline_simple", {{"WGPUDevice", "device_handle"}, {"WGPUShaderModule", "vs_module_handle"}, {"WGPUShaderModule", "fs_module_handle"}, {"string", "vs_entry"}, {"string", "fs_entry"}, {"string", "format"}}, "WGPURenderPipeline"},
    {"wgpu", "set_pipeline", {{"WGPURenderPass", "pass_handle"}, {"WGPURenderPipeline", "pipeline_handle"}}, ""},
    {"wgpu", "draw", {{"WGPURenderPass", "pass_handle"}, {"int32", "vertex_count"}, {"int32", "instance_count"}, {"int32", "first_vertex"}, {"int32", "first_instance"}}, ""},
};

const size_t SCHEMA_COUNT = 124;

const char* HANDLES[] = {
    "Audio",
    "Canvas",
    "CanvasContext2D",
    "DOMElement",
    "FetchRequest",
    "Image",
    "WGPUAdapter",
    "WGPUCommandBuffer",
    "WGPUCommandEncoder",
    "WGPUContext",
    "WGPUDevice",
    "WGPUQueue",
    "WGPURenderPass",
    "WGPURenderPipeline",
    "WGPUShaderModule",
    "WGPUTextureView",
    "WebGLBuffer",
    "WebGLContext",
    "WebGLProgram",
    "WebGLShader",
    "WebGLUniform",
    "WebSocket",
};

const size_t HANDLE_COUNT = 22;

const std::pair<const char*, const char*> HANDLE_INHERITANCE[] = {
    { "Audio", "DOMElement" },
    { "Canvas", "DOMElement" },
    { "Image", "DOMElement" },
    { nullptr, nullptr }
};

} // namespace coi
